const indianStates = [
  { name: "ANDAMAN AND NICOBAR ISLANDS", code: "AN" },
  { name: "ANDHRA PRADESH", code: "AP" },
  { name: "ARUNACHAL PRADESH", code: "AR" },
  { name: "ASSAM", code: "AS" },
  { name: "BIHAR", code: "BR" },
  { name: "CHANDIGARH", code: "CH" },
  { name: "CHHATTISGARH", code: "CT" },
  { name: "DADRA AND NAGAR HAVELI", code: "DN" },
  { name: "DAMAN AND DIU", code: "DD" },
  { name: "DELHI", code: "DL" },
  { name: "GOA", code: "GA" },
  { name: "GUJARAT", code: "GJ" },
  { name: "HARYANA", code: "HR" },
  { name: "HIMACHAL PRADESH", code: "HP" },
  { name: "JAMMU AND KASHMIR", code: "JK" },
  { name: "JHARKHAND", code: "JH" },
  { name: "KARNATAKA", code: "KA" },
  { name: "KERALA", code: "KL" },
  { name: "LAKSHADWEEP", code: "LD" },
  { name: "MADHYA PRADESH", code: "MP" },
  { name: "MAHARASHTRA", code: "MH" },
  { name: "MANIPUR", code: "MN" },
  { name: "MEGHALAYA", code: "ML" },
  { name: "MIZORAM", code: "MZ" },
  { name: "NAGALAND", code: "NL" },
  { name: "ODISHA", code: "OR" },
  { name: "PUDUCHERRY", code: "PY" },
  { name: "PUNJAB", code: "PB" },
  { name: "RAJASTHAN", code: "RJ" },
  { name: "SIKKIM", code: "SK" },
  { name: "TAMIL NADU", code: "TN" },
  { name: "TELANGANA", code: "TG" },
  { name: "TRIPURA", code: "TR" },
  { name: "UTTAR PRADESH", code: "UP" },
  { name: "UTTARAKHAND", code: "UT" },
  { name: "WEST BENGAL", code: "WB" },
];

export default indianStates;
